# Generated by Django 5.0.6 on 2024-06-08 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0002_menuitem_restaurantorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantorder',
            name='address',
        ),
    ]
