# Generated by Django 5.0.6 on 2024-06-09 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0006_restaurantorder_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantorder',
            name='restaurant',
        ),
    ]
