# Generated by Django 5.0.6 on 2024-06-08 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_app', '0001_initial'),
        ('driver_app', '0001_initial'),
        ('restaurant_app', '0002_menuitem_restaurantorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('assigned_driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='driver_app.driver')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer_app.customer')),
                ('restaurant_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.restaurantorder')),
            ],
        ),
    ]
